name: Heartbeat to Ingestion API

on:
  workflow_dispatch:        # show "Run workflow" button
  schedule:
    - cron: "*/5 * * * *"   # also run every 5 minutes

jobs:
  send-heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Send sample telemetry
        env:
          INGEST_URL_BASE: ${{ secrets.INGEST_URL_BASE }}
          INGEST_KEY: ${{ secrets.INGEST_KEY }}
        run: |
          curl -sS -X POST "$INGEST_URL_BASE/ingest/telemetry" \
            -H "Content-Type: application/json" \
            -H "X-INGEST-KEY: $INGEST_KEY" \
            -d '{
              "v": 1,
              "site_id": "T3",
              "device_id": "heartbeat",
              "ts": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'",
              "src": "heartbeat",
              "metrics": [
                {"metric":"pv_power_w","value":1000,"unit":"W"}
              ]
            }'
