name: Heartbeat to Ingestion API

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:       # manual trigger

jobs:
  send-heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Send heartbeat to ingestion API
        run: |
          echo "Sending heartbeat to ingestion API..."
          RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}\n" -X POST \
            -H "Content-Type: application/json" \
            -d '[
              {
                "site_id": "T3",
                "device_id": null,
                "metric": "heartbeat",
                "value": 1,
                "unit": "count",
                "src": "heartbeat"
              }
            ]' \
            https://ingestion-api-x84z.onrender.com/ingest/telemetry)

          echo "Full API response:"
          echo "$RESPONSE"

          STATUS=$(echo "$RESPONSE" | grep HTTP_STATUS | cut -d':' -f2)

          if [ "$STATUS" != "200" ]; then
            echo "❌ Heartbeat failed with status $STATUS"
            exit 1
          else
            echo "✅ Heartbeat sent successfully"
          fi
