name: Victron Connector

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:         # allow manual runs

jobs:
  run-victron-connector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Victron connector
        env:
          INGEST_URL_BASE: ${{ secrets.INGEST_URL_BASE }}
          INGEST_KEY: ${{ secrets.INGEST_KEY }}
          VICTRON_TOKEN: ${{ secrets.VICTRON_TOKEN }}
          VICTRON_INSTALLATION_ID: ${{ secrets.VICTRON_INSTALLATION_ID }}
        run: |
          echo "Running Victron connector for site $VICTRON_INSTALLATION_ID"
          python victron_connector.py --site-id "$VICTRON_INSTALLATION_ID" --since-minutes 10
